const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, Table, TableRow, TableCell, TextRun, HeadingLevel, AlignmentType, WidthType, BorderStyle } = require('docx');
const Lot = require('../models/Lot');
const Guest = require('../models/Guest');

// Helper to get all guests in a lot
async function getLotWithGuests(lotId) {
  const lot = await Lot.findById(lotId);
  if (!lot) throw new Error('Lot not found');
  const guests = await Guest.find({ lotId }).sort({ serialNumber: 1, createdAt: 1 });
  return { lot, guests };
}

// GET export lot as PDF
router.get('/pdf/:lotId', async (req, res) => {
  try {
    const { lot, guests } = await getLotWithGuests(req.params.lotId);

    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${lot.lotName.replace(/\s+/g, '_')}_guests.pdf"`);
    doc.pipe(res);

    // Header
    doc.rect(0, 0, doc.page.width, 90).fill('#1a1a2e');
    doc.fillColor('#f0c040')
       .fontSize(24)
       .font('Helvetica-Bold')
       .text('🎊 Marriage Guest List', 40, 20, { align: 'center' });
    doc.fillColor('#ffffff')
       .fontSize(14)
       .font('Helvetica')
       .text(lot.lotName, 40, 50, { align: 'center' });
    if (lot.description) {
      doc.fillColor('#cccccc')
         .fontSize(10)
         .text(lot.description, 40, 68, { align: 'center' });
    }

    doc.moveDown(3);
    doc.fillColor('#333333')
       .fontSize(10)
       .text(`Total Guests: ${guests.length}   |   Generated: ${new Date().toLocaleDateString('en-IN')}`, { align: 'right' });
    doc.moveDown(1);

    // Table header
    const tableTop = doc.y;
    const colWidths = [40, 110, 110, 110, 100, 100];
    const colX = [40];
    colWidths.slice(0, -1).forEach((w, i) => colX.push(colX[i] + w));
    const headers = ['#', 'First Name', 'Father Name', 'Surname', 'Mobile', 'Place'];

    // Draw header row
    doc.rect(40, tableTop, 515, 22).fill('#1a1a2e');
    headers.forEach((h, i) => {
      doc.fillColor('#f0c040')
         .fontSize(9)
         .font('Helvetica-Bold')
         .text(h, colX[i] + 3, tableTop + 7, { width: colWidths[i] - 6, ellipsis: true });
    });

    // Draw guest rows
    let rowY = tableTop + 22;
    guests.forEach((guest, idx) => {
      if (rowY > doc.page.height - 60) {
        doc.addPage();
        rowY = 40;
        // Repeat header
        doc.rect(40, rowY, 515, 22).fill('#1a1a2e');
        headers.forEach((h, i) => {
          doc.fillColor('#f0c040')
             .fontSize(9)
             .font('Helvetica-Bold')
             .text(h, colX[i] + 3, rowY + 7, { width: colWidths[i] - 6, ellipsis: true });
        });
        rowY += 22;
      }

      const rowColor = idx % 2 === 0 ? '#f9f9f9' : '#ffffff';
      doc.rect(40, rowY, 515, 20).fill(rowColor);

      const rowData = [
        String(idx + 1),
        guest.firstName || '-',
        guest.fatherName || '-',
        guest.surname || '-',
        guest.mobileNumber || '-',
        guest.place || '-',
      ];
      rowData.forEach((val, i) => {
        doc.fillColor('#222222')
           .fontSize(8.5)
           .font('Helvetica')
           .text(val, colX[i] + 3, rowY + 6, { width: colWidths[i] - 6, ellipsis: true });
      });

      // Row border
      doc.rect(40, rowY, 515, 20).stroke('#e0e0e0');
      rowY += 20;
    });

    // Footer
    doc.moveDown(2);
    doc.fillColor('#888888')
       .fontSize(8)
       .text('Generated by Marriage Guest List System', 40, doc.page.height - 30, { align: 'center' });

    doc.end();
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// GET export lot as Word (.docx)
router.get('/word/:lotId', async (req, res) => {
  try {
    const { lot, guests } = await getLotWithGuests(req.params.lotId);

    const headerRow = new TableRow({
      children: ['#', 'First Name', 'Father Name', 'Surname', 'Mobile Number', 'Place'].map(
        (text) =>
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text, bold: true, color: 'F0C040', size: 20 })],
                alignment: AlignmentType.CENTER,
              }),
            ],
            shading: { fill: '1A1A2E' },
            margins: { top: 80, bottom: 80, left: 80, right: 80 },
          })
      ),
    });

    const dataRows = guests.map((guest, idx) =>
      new TableRow({
        children: [
          String(idx + 1),
          guest.firstName || '-',
          guest.fatherName || '-',
          guest.surname || '-',
          guest.mobileNumber || '-',
          guest.place || '-',
        ].map(
          (val) =>
            new TableCell({
              children: [
                new Paragraph({
                  children: [new TextRun({ text: val, size: 18 })],
                  alignment: AlignmentType.LEFT,
                }),
              ],
              shading: { fill: idx % 2 === 0 ? 'F5F5F5' : 'FFFFFF' },
              margins: { top: 60, bottom: 60, left: 80, right: 80 },
            })
        ),
      })
    );

    const table = new Table({
      rows: [headerRow, ...dataRows],
      width: { size: 100, type: WidthType.PERCENTAGE },
    });

    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text: '🎊 Marriage Guest List',
                  bold: true,
                  size: 48,
                  color: '1A1A2E',
                }),
              ],
              heading: HeadingLevel.HEADING_1,
              alignment: AlignmentType.CENTER,
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: lot.lotName,
                  bold: true,
                  size: 32,
                  color: '8B0000',
                }),
              ],
              alignment: AlignmentType.CENTER,
            }),
            lot.description
              ? new Paragraph({
                  children: [new TextRun({ text: lot.description, size: 22, italics: true })],
                  alignment: AlignmentType.CENTER,
                })
              : new Paragraph(''),
            new Paragraph({
              children: [
                new TextRun({
                  text: `Total Guests: ${guests.length}   |   Generated: ${new Date().toLocaleDateString('en-IN')}`,
                  size: 18,
                  color: '666666',
                }),
              ],
              alignment: AlignmentType.RIGHT,
            }),
            new Paragraph(''),
            table,
            new Paragraph(''),
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Generated by Marriage Guest List System',
                  size: 16,
                  color: '999999',
                  italics: true,
                }),
              ],
              alignment: AlignmentType.CENTER,
            }),
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="${lot.lotName.replace(/\s+/g, '_')}_guests.docx"`);
    res.send(buffer);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
